# === JEKYLL CONFIG ===

remote_theme: barryclark/jekyll-now

# === BASIC INFO ===

name: Allen Morin
description: Game Programmer & Systems Designer
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

# === SOCIAL FOOTER LINKS ===
footer-links:
  github: Allen-Morin
  twitter: # Add your handle if you want, e.g. AllenCodes
  instagram: # Optional
  linkedin: # Optional
  rss: true

# === COMMENTS (Optional) ===
# Create a free account at disqus.com and add your shortname here if you want comments enabled
disqus: 

# === ANALYTICS (Optional) ===
# Get a Google Analytics ID and paste it here to track page views
google_analytics: 

# === SITE URL ===
# This should be your actual GitHub Pages URL
url: https://allen-morin.github.io
baseurl: ""  # Leave blank since you're using a personal GitHub Pages repo

# === PERMALINKS ===
permalink: /:title/

# === JEKYLL + MARKDOWN SETTINGS ===
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# === SASS OPTIONS ===
sass:
  style: :expanded

# === PLUGINS ===
gems:
  - jekyll-sitemap
  - jekyll-feed

# === EXCLUDED FILES ===
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME